- hosts: "{{ env }}"
  become: yes
  tasks:
    - name: Pull latest Docker image
      docker_image:
        name: microlending-app
        tag: latest
        source: pull

    - name: Stop existing container if running
      docker_container:
        name: microlending-app
        state: absent

    - name: Run new container
      docker_container:
        name: microlending-app
        image: microlending-app:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
